### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/website#262]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [x] website_analytics_piwik - By @astirpe - #338 
- [x] website_anchor_smooth_scroll - By @Tardo #347 
- [x] website_canonical_url - By @simahawk - #449 
- [ ] website_backend_views
- [ ] website_blog_facebook_comment
- [ ] website_blog_mgmt
- [x] website_breadcrumb - By @JonathanNEMRY - #339 
- [x] website_container_fluid - By @Tardo #348
- [x] website_cookie_notice - By @hurrinico - #309 
- [x] website_crm_quick_answer - By @chienandalu - #356 
- [x] website_crm_privacy_policy - By @Yajo #359 
- [ ] website_crm_recaptcha - By @lasley - #268 
- [x] ~~website_event_register_free~~ Included in core
- [x] ~~website_event_register_free_with_sale~~ Included in core
- [x] website_field_autocomplete - By @lasley - #269 
- [ ] website_form_recaptcha - By @lasley - #267 
- [ ] website_forum_censored
- [ ] website_hr_department - By @JonathanNEMRY - #335 
- [x] website_legal_page - By @lasley  - #353  
- [x] website_logo - By @chienandalu - #357 
- [ ] website_menu_by_user_status - By @GillesTephaneMeyomesse - #324 
- [ ] website_menu_multilang - By @reinka - #352 
- [x] website_no_crawler - By @RoelAdriaans-B-informed - #301
- [x] website_odoo_debranding - By @Yajo - #360 
- [x] ~~website_payment_v10~~ - Removed as now is in core
- [ ] website_portal_contact - By @osotranquilo #350
- [ ] website_portal_purchase - By @Tardo - #351
- [x] ~~website_portal_v10~~ - Removed as now is in core
- [x] ~~website_sale_collapse_categories~~ - Removed as it's integrated on v9 core
- [x] website_sale_order_company - Moved to OCA/e-commerce - By @reinka https://github.com/OCA/e-commerce/pull/180
- [ ] website_sale_unsaleable_options - To be moved to OCA/e-commerce
- [x] website_seo_redirection - ~~By @mobilizer - #294~~ - By @lasley - #329 
- [x] website_signup_legal_page_required - By @Yajo - #249 
- [x] website_snippet_anchor - @Yajo #361 
- [x] website_snippet_country_dropdown - By @HaTry #349

**Comment by eugen-don** [comment]
Hi @pedrobaeza 
could you assing me to the module migration.
I have seen the issue https://github.com/OCA/website/issues/293

In my opinion website_legal_page is one of the general modules any startup/ small business needs to stay legal and avoid  written warnings... especially important for startups who have not yet acquired a legal protection insurance...

Could you assign me to the migration of this module... I will try my luck with this one as well tomorrow...

**Comment by pedrobaeza** [comment]
But there's already a PR in progress. See this issue that is mentioned.

**Comment by eugen-don** [comment]
OK, sorry for the confusion, Iam still new to github...

**Comment by JonathanNEMRY** [comment]
website_hr_department https://github.com/OCA/website/pull/335

**Comment by dreambits** [comment]
Maybe i missed something but is website_snippet_anchor not suppose to be part of migration to v10 ? 
If not so, can I try getting my hands dirty with it and see if I contribute to migrate it ?

**Comment by lasley** [comment]
@dreambits - looks like it was migrated to 9 after v10 was created, so it didn't make it into this ticket. I added it now and tagged you to it!

**Comment by astirpe** [comment]
website_analytics_piwik https://github.com/OCA/website/pull/338

**Comment by dreambits** [comment]
Okay .. thanks @lasley

**Comment by JonathanNEMRY** [comment]
https://github.com/OCA/website/pull/339/files#diff-c7e737a062366a24a8b497ff449a4812R12 done need reviews

**Comment by Tardo** [comment]
I'm going to migrate 'website_anchor_smooth_scroll' to version 10.0

**Comment by HaTry** [comment]
I'm going to migrate 'website_snippet_country_dropdown' to version 10.0

**Comment by Tardo** [comment]
I'm going to migrate 'website_container_fluid' to version 10.0

**Comment by reinka** [comment]
[PR in Odoo/e-commerce](https://github.com/OCA/e-commerce/pull/180) for `website_sale_order_company`

**Comment by zeroheure** [comment]
migrating website canonical url to Odoo 10 https://github.com/OCA/website/pull/413
(I didn't know about reinka port). This one is simpler. Description of complete SEO problem added.

**Comment by eLBati** [comment]
website_signup_legal_page_required: https://github.com/OCA/website/pull/467
