### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/website#388]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x] website_analytics_piwik - By @astirpe - #404 
- [x] website_anchor_smooth_scroll - By @njeudy - #407 
- [ ] website_backend_views
- [ ] website_blog_category
- [ ] website_blog_facebook_comment
- [ ] website_blog_mgmt
- [ ] website_breadcrumb
- [x] website_canonical_url - By @simahawk - #460 
- [ ] website_container_fluid
- [x] website_cookie_notice - By @njeudy - #408 
- [x] website_crm_privacy_policy - By @cubells - #446 
- [ ] website_crm_quick_answer - By @wpichler - #473
- [x] website_crm_recaptcha - By @dbo-odoo - #396 
- [ ] website_field_autocomplete - By @dbo-odoo - #397 
- [x] website_form_builder - By @Daemo00 - #476 
- [x] website_form_metadata - By @chienandalu - #464
- [x] website_form_recaptcha - ~~By @dbo-odoo - #395~~ - By @hmrodrigues  - #458 
- [ ] website_forum_censored
- [x] website_google_tag_manager - By @cristinamartinrod - #524 
- [ ] website_hr_department
- [x] website_legal_page - By @nadiaafa - #403 
- [x] website_logo - By @ernestotejeda - #470 
- [x] website_menu_by_user_status - By @ddufresne -  #429 
- [ ] website_menu_multilang
- [x] website_multi_theme - By @yelizariev - #398 
- [x] website_no_crawler - By @ernestotejeda - #471 
- [x] website_odoo_debranding - By @ddufresne - #428 
- [ ] website_portal_contact
- [ ] website_portal_purchase
- [x] website_sale_hide_empty_category - By @remytms - OCA/e-commerce#256
- [ ] website_sale_line_total - To be moved to OCA/e-commerce
- [ ] website_sale_order_company - To be moved to OCA/e-commerce
- [ ] website_sale_unsaleable_options - To be moved to OCA/e-commerce
- [x] website_seo_redirection - ~~To see what features aren't yet in standard, as some of them are already.~~ No more needed - #462 
- [x] website_snippet_anchor - By @tarteo - #420 
- [ ] website_snippet_barcode
- [ ] website_snippet_country_dropdown
- [ ] website_snippet_data_slider - By @smurf-U - #401

**Comment by bouvyd** [comment]
`website_blog_mgmt` seems mostly depreciated by odoo/odoo@a4d8cf9ead31a8e2160229672ae89ff7485fe753 (since version 10.0 in fact)

**Comment by bouvyd** [comment]
`website_form_recaptcha`: #395 
 `website_crm_recaptcha`: #396

**Comment by bouvyd** [comment]
`website_field_autocomplete`:  #397

**Comment by smurf-U** [comment]
https://github.com/OCA/website/pull/401 website_snippet_data_slider

**Comment by nadiaafa** [comment]
@pedrobaeza i will work on website_legal_page and website_cookie_notice

**Comment by astirpe** [comment]
website_analytics_piwik https://github.com/OCA/website/pull/404

**Comment by njeudy** [comment]
@pedrobaeza : website_anchor_smooth_scroll #407

**Comment by njeudy** [comment]
@pedrobaeza website_cookie_notice  #408

**Comment by tarteo** [comment]
website_snippet_anchor #420

**Comment by ddufresne** [comment]
I will work on website_odoo_debranding

**Comment by ddufresne** [comment]
website_odoo_debranding https://github.com/OCA/website/pull/428

**Comment by ddufresne** [comment]
website_menu_by_user_status https://github.com/OCA/website/pull/429

**Comment by Daemo00** [comment]
website_form_builder https://github.com/OCA/website/pull/476

**Comment by emagdalenaC2i** [comment]
@pedrobaeza Please, could you move up website_form_builder in the list so that it is sorted correctly in alphabetical order

Please add to the list website_form_metadata - By @chienandalu - #464 that is already migrated and merged

Please check website_no_crawler - By @ernestotejeda - #471

Please check website_sale_hide_empty_category - By @remytms - OCA/e-commerce#256

There is a PR for the migration of website_crm_quick_answer - By @wpichler - #473

**Comment by emagdalenaC2i** [comment]
@pedrobaeza Please, check website_canonical_url - By @simahawk - #460 because it is already merged

**Comment by kwoychesko** [comment]
`website_breadcrumbs`: #880
