### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/website#85]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] website_analytics_piwik - https://github.com/OCA/website/pull/145
- [x] website_anchor_smooth_scroll - By obulkin - #243
- [ ] website_backend_views
- [ ] website_blog_facebook_comment
- [x] website_blog_excerpt_img - By @Yajo - #298 
- [x] website_blog_mgmt - By @sergio-teruel - #147
- [x] website_blog_share - By @cubells - #291 
- [x] website_breadcrumb - By @khaeusler - #216 
- [x] website_canonical_url - By @Yajo - #299
- [x] website_crm_privacy_policy - By @Yajo - #302
- [ ] website_calendar_snippet - It should be renamed to _website_snippet_calendar_ - By @tarteo - #317 
- [x] website_container_fluid - By @Yajo - #300
- [x] website_cookie_notice - #195
- [x] website_crm_quick_answer - By @Yajo - #321
- [x] ~~website_event_register_free~~ - In core
- [x] ~~website_event_register_free_with_sale~~ - In core
- [ ] website_hr_department
- [x] website_img_bg_style - By @cubells - #290 
- [x] website_legal_page - By @lasley - #194
- [x] website_logo - ~~By @lasley - #192~~ - By @StephanRozendaal - #245 
- [ ] website_menu_by_user_status - By @hurrinico - #275 
- [ ] website_menu_multilang
- [x] website_no_crawler - By @RoelAdriaans-B-informed - #100
- [ ] website_portal_purchase - By @lukebranch
- [ ] website_sale_order_company - To be moved to OCA/e-commerce
- [ ] website_sale_unsaleable_options - To be moved to OCA/e-commerce
- [X] website_sale_vat_required - To be moved to OCA/e-commerce - By @Yajo - https://github.com/OCA/e-commerce/pull/174
- [x] ~~website_sale_collapse_categories~~ - Removed as it's integrated on v9 core
- [x] website_seo_redirection - By @lasley - #219
- [ ]  website_signup_legal_page_required - By @archetipo - #272 
- [x] website_snippet_anchor - By @Yajo - #288
- [x] website_snippet_big_button - By @Yajo - #303 
- [x] website_snippet_marginless_gallery - By @Yajo - #368 
- [ ] website_supplier_list - By @mikevhe18 - #286

**Comment by rafaelbn** [comment]
As  website_portal has been a backport, must it be migrated?

**Comment by pedrobaeza** [comment]
No, that modules should be removed in a PR to clean this branch.

**Comment by rafaelbn** [comment]
Ref with https://github.com/OCA/website/issues/119

[9.0] Moving modules from v8 OCA/website to v9 OCA/e-commerce #119 

As discussed we must take this moment of moving to v9 to move modules to the correct repository.

All modules which depends from website_sale must be moved to OCA/e-commerce:

```
website_event_register_free_with_sale
website_sale_collapse_categories
website_sale_order_company
website_sale_unsaleable_options
website_sale_vat_required
```

If you agree this 5 modules will go to https://github.com/OCA/e-commerce/tree/9.0

**Comment by lukebranch** [comment]
@pedrobaeza @rafaelbn ,

I just wanted to check with you both. Are there any plans to port:

website_portal_purchase

to version 9.0? This is a very useful module for many B2B companies and can be easily extended with extra features.

If there is no roadmap to port this to version 9.0 I will work on my own port, i'd just like to check if there is any current work on this before I get started.

**Comment by pedrobaeza** [comment]
Not for now, @lukebranch, so I assign you the task in this issue. We'll review the PR when done.

**Comment by lukebranch** [comment]
@pedrobaeza ,

Thanks, i'm not sure my port will be up to OCA standards, however if you'll bear with me I will do my best to match your requirements in the PR.

**Comment by pedrobaeza** [comment]
I'm sure you can do it! I'll guide you in any doubt you have.

**Comment by lukebranch** [comment]
@pedrobaeza ,

Thank you. I'll begin work on something next weekend.

**Comment by yajo** [comment]
I will migrate `website_portal_purchase`.

**Comment by yajo** [comment]
Oh I did not see that @lukebranch has it. How is your work going on? Thanks.

**Comment by yajo** [comment]
@lukebranch is silent, I take the job.

**Comment by lukebranch** [comment]
@Yajo ,

My apologies, i've been too busy to even get started on that project.

I plan to build an extension to the module later on that will allow manufacturers/suppliers to login and input what is being sent and what is going to be a backorder (this is a common use case in a few of our companies).

I'd be very interested to checkout a PR once you've started work on this.

**Comment by yajo** [comment]
my work is started already: https://github.com/Tecnativa/website/tree/9.0-website_portal_purchase-migration. I'll mention you when I pr

**Comment by lukebranch** [comment]
@Yajo ,

Thanks.

**Comment by yajo** [comment]
I'll start with `website_product_supplier`, and I will rename it to `website_portal_purchase_product` in v9.

**Comment by lukebranch** [comment]
@Yajo ,

Thanks for the update, I'm going to start testing your backport of the website_portal from v10 this week.

**Comment by yajo** [comment]
I'm starting `website_snippet_country_dropdown`

**Comment by laurent2a** [comment]
Hello,
I need **website_backend_views** module for à personal project on V9, so i am going to work on the module migration. 
Do you have any idea of what can cause the installation problem on V9 ?
Laurent

**Comment by lasley** [comment]
Hi @laurent2a - I have tried that upgrade a few times and ran into issues, although I can't find my documentation as to what. If you would like to save a lot of work, feel free to base off my branch - https://github.com/laslabs/website/tree/feature/9.0/upgrade-website_backend_views

FYI we're working on an initiative to break the backend sandbox in OCA/web#402, which should solve the problem noted in `website_backend_views` docs regarding public user session. It may actually deprecate the module, depending on how well we do - but probably not.

**Comment by laurent2a** [comment]
Ok thanks a lot lasley, I look at your branch.

**Comment by laurent2a** [comment]
Hi lasley,
I have just tryed your banch last commit: ec3ee47c62007a071791c9cebcad97eb8740af7f on windows7, and get this error message on installation :

```
return self.models[model_name]
KeyError: 'website.qweb'
> c:\users\laurent\workspace\odoo-9.0\openerp\modules\registry.py(84)__getitem__()
-> return self.models[model_name]
(Pdb)
```

Is there a better place for this discussion ?

**Comment by tarteo** [comment]
I'll port **website_calendar_snippet** in the upcoming weeks.

**Comment by yajo** [comment]
I'll migrate website_sale_vat_required and put it in e-commerce.
